name: eventhub_backend
description: Backend para la gestiÃ³n de eventos desarrollado en Dart.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
